spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/school_inventory
      database: school_inventory

  servlet:
    multipart:
      enabled: true
      max-file-size: 5MB
      max-request-size: 5MB

server:
  port: 8080
file:
  upload-dir: uploads/students



# Your existing MongoDB and other configurations
# ...
